### ISSUE TITLE
TLS 1.3

### ISSUE THREAD

**Issue by smyslov** [smyslov/rfc8229bis#3]
When speaking about TLS the draft currently only describes TLS 1.2. I've added a couple of obvious remarks concerning TLS 1.3 (e.g. reference RFC8446 and note that we cannot use NULL cipher in TLS 1.3, as was previously suggested in the draft). The question is - do we need to also add a full example of using IKE over TLS 1.3 as it is done for TLS 1.2 in the Appendix? Or the current diagrams are sufficient?

**Comment by tfpauly** [comment]
Thanks for mentioning TLS 1.3 there!

I'm not sure we'd need diagrams for *both* TLS 1.2 and TLS 1.3. The difference for IKE is not very significant. However, we could update to only show a diagram for TLS 1.3. Thoughts?

**Comment by smyslov** [comment]
I don't mind.
